export const beats = [
    {
        "id": 14,
        "typeId": 1,
        "title": "Beat 1",
        "artist": "Artist 1",
        "locationId": 1,
        "locationName": "",
        "order": 1,
        "mp3Filename": "5f4a33b83cb28205531635.mp3",
        "oggFilename": "5f4a33f497dce190395190.ogg",
        "fallbackFilename": "5f4a33b83cb28205531635.mp3",
        "mp3Url": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a33b83cb28205531635.mp3",
        "oggUrl": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a33f497dce190395190.ogg",
        "fallbackUrl": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a33b83cb28205531635.mp3",
        "videoUrl": "",
        "videoId": ""
    },
    {
        "id": 18,
        "typeId": 1,
        "title": "Beat 2",
        "artist": "Artist 2",
        "locationId": 1,
        "locationName": "",
        "order": 2,
        "mp3Filename": "5f4a3873c7115511605417.mp3",
        "oggFilename": "5f4a3873c712f278815583.ogg",
        "fallbackFilename": "5f4a3873c7115511605417.mp3",
        "mp3Url": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a3873c7115511605417.mp3",
        "oggUrl": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a3873c712f278815583.ogg",
        "fallbackUrl": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a3873c7115511605417.mp3",
        "videoUrl": "",
        "videoId": ""
    },
    {
        "id": 19,
        "typeId": 1,
        "title": "Beat 3",
        "artist": "Artist 3",
        "locationId": 1,
        "locationName": "",
        "order": 3,
        "mp3Filename": "5f4a388b92d8c949136818.mp3",
        "oggFilename": "5f4a388b92d91987983068.ogg",
        "fallbackFilename": "5f4a388b92d8c949136818.mp3",
        "mp3Url": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a388b92d8c949136818.mp3",
        "oggUrl": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a388b92d91987983068.ogg",
        "fallbackUrl": "http:\/\/wolfsbane.local:8080\/wp-content\/plugins\/wolfsbane-admin\/\/Upload\/Media\/5f4a388b92d8c949136818.mp3",
        "videoUrl": "",
        "videoId": ""
    }
];

export const beatsLocalhost = [
    {
        "id": 14,
        "typeId": 1,
        "title": "Beat 1",
        "artist": "Artist 1",
        "locationId": 1,
        "locationName": "",
        "order": 1,
        "mp3Filename": "blow-my-mind-davido-chris-brown.mp3",
        "oggFilename": "blow-my-mind-davido-chris-brown.ogg",
        "fallbackFilename": "blow-my-mind-davido-chris-brown.mp3",
        "mp3Url": "\/wp-content\/themes\/wolfsbanetheme\/template-v2\/wwwroot\/audio\/blow-my-mind-davido-chris-brown.mp3",
        "oggUrl": "\/audio\/blow-my-mind-davido-chris-brown.ogg",
        "fallbackUrl": "\/audio\/blow-my-mind-davido-chris-brown.mp3",
        "videoUrl": "",
        "videoId": ""
    },
    {
        "id": 18,
        "typeId": 1,
        "title": "Beat 2",
        "artist": "Artist 2",
        "locationId": 1,
        "locationName": "",
        "order": 2,
        "mp3Filename": "blow-my-mind-davido-chris-brown.mp3",
        "oggFilename": "blow-my-mind-davido-chris-brown.ogg",
        "fallbackFilename": "blow-my-mind-davido-chris-brown.mp3",
        "mp3Url": "\/audio\/blow-my-mind-davido-chris-brown.mp3",
        "oggUrl": "\/audio\/blow-my-mind-davido-chris-brown.ogg",
        "fallbackUrl": "\/audio\/blow-my-mind-davido-chris-brown.mp3",
        "videoUrl": "",
        "videoId": ""
    },
    {
        "id": 19,
        "typeId": 1,
        "title": "Beat 3",
        "artist": "Artist 3",
        "locationId": 1,
        "locationName": "",
        "order": 3,
        "mp3Filename": "blow-my-mind-davido-chris-brown.mp3",
        "oggFilename": "blow-my-mind-davido-chris-brown.ogg",
        "fallbackFilename": "blow-my-mind-davido-chris-brown.mp3",
        "mp3Url": "\/audio\/blow-my-mind-davido-chris-brown.mp3",
        "oggUrl": "\/audio\/blow-my-mind-davido-chris-brown.ogg",
        "fallbackUrl": "\/audio\/blow-my-mind-davido-chris-brown.mp3",
        "videoUrl": "",
        "videoId": ""
    }
];